### ISSUE TITLE
ES Version

### ISSUE THREAD

**Issue by RobinMalfait** [lukeed/obj-str#1]
What is the minimum version of ES that is required?

Because we can make that even more tiny like this:

```js
export default (obj = {}) => Object.keys(obj).filter(k => obj[k]).join(' ');
```

**Comment by lukeed** [comment]
HI, thanks!

I had nearly this exact code at first, but it's **much** slower (18M op/s vs 4.6M op/s) because of the `Object.keys`. And, depending on how others configure their compiler, it _can_ inflate to being more bytes anyway.

It's a bummer, huh? 😜

**Comment by lukeed** [comment]
With Node 8+, this becomes _much_ faster. However, this is limited to actually using Node 8+ or waiting for browsers to adopt the changes.

That said, should you choose to go that route, I would still heavily recommend using [`@arr/filter.mutate`](https://github.com/lukeed/arr/tree/master/packages/filter.mutate) instead of `Array.p.filter` directly.
